buildscript
{
    repositories
    {
        maven
        {
            url = 'https://maven.minecraftforge.net/'
        }

        maven
        {
            url = 'https://repo.spongepowered.org/maven'
        }

        mavenCentral()
    }

    dependencies
    {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

repositories
{
    flatDir
    {
        dirs 'libs'
    }
    maven
    {
        url "https://cursemaven.com"
    }
}

apply plugin: 'net.minecraftforge.gradle'

apply plugin: 'eclipse'
apply plugin: 'maven-publish'

apply plugin: 'org.spongepowered.mixin'

// File metadata
version = '0.1'
group = 'org.imesense.dynamicspawncontrol.modid'
archivesBaseName = 'dynamicspawncontrol'

// Java version
sourceCompatibility =
targetCompatibility =
compileJava.sourceCompatibility =
compileJava.targetCompatibility =
    '1.8'

minecraft
{
    // Mappings settings of Minecraft
    mappings channel: 'snapshot', version: '20171003-1.12'

    // Default run configurations
    runs
    {
        client
        {
            workingDirectory project.file('run')

            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            // Load LoadingPluginCore
            property 'fml.coreMods.load', 'org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore'

            // Mixins
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }

        server
        {
            // Recommended logging data for a userdev environment
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            // Recommended logging level for the console
            property 'forge.logging.console.level', 'debug'

            // Load LoadingPluginCore
            property 'fml.coreMods.load', 'org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore'

            // Mixins
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }
    }
}

mixin
{
    add sourceSets.main, 'mixins.dynamicspawncontrol.refmap.json'
}

dependencies
{
    // Specify the version of Minecraft to use
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    // Use lombok lib
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    implementation 'org.slf4j:slf4j-simple:1.7.36'

    // Use mixins lib
    implementation 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // Use core mod #1 DivineRPG
    implementation fg.deobf("curse.maven:official-divinerpg-363543:2937175")

    // Use core mod #2 SRParasites
    implementation fg.deobf("curse.maven:scape-and-run-parasites-348025:5370258")

    // Actual version of builder GSON
    implementation 'com.google.code.gson:gson:2.8.9'

    // Use Byte buddy lib
    implementation 'net.bytebuddy:byte-buddy:1.12.9'

    // Use core mod #3 Special-Mobs
    implementation fg.deobf("curse.maven:special-mobs-59968:3320102")

    // Use additional mod #4 Modern-Warfare-Mod
    implementation fg.deobf("curse.maven:vics-modern-warfare-mod-243788:4415481")
}

// Get properties into the manifest for reading by the runtime
jar
{
    manifest
    {
        attributes([
            "Specification-Title": "dynamicspawncontrol",
            "Specification-Vendor": "imesense",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"imesense",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "FMLCorePlugin": "org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore",
            "FMLCorePluginContainsFMLMod": "true",
            "MixinConfigs": "mixins.dynamicspawncontrol.json"
        ])
    }
}

// Preferred method to reobfuscate JAR file
jar.finalizedBy('reobfJar')

publishing
{
    publications
    {
        mavenJava(MavenPublication)
        {
            artifact jar
        }
    }

    repositories
    {
        maven
        {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// Enable packaging of metadata and resources
sourceSets
{
    main
    {
        output.resourcesDir = output.classesDir
    }
}

// Mixins
compileJava
{
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs +=
    [
        "-AdefaultObfuscationEnv=searge",
        "-AoutRefMap=mixins.dynamicspawncontrol.refmap.json"
    ]
}