buildscript
{
    repositories
    {
        maven
        {
            url = 'https://maven.minecraftforge.net/'
        }

        maven
        {
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }

        mavenCentral()
    }

    dependencies
    {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7.+'
    }
}

repositories
{
    flatDir
    {
        dirs 'libs'
    }
    maven
    {
        url "https://cursemaven.com"
    }
}

apply plugin: 'net.minecraftforge.gradle'

apply plugin: 'eclipse'
apply plugin: 'maven-publish'

apply plugin: 'org.spongepowered.mixin'

// File metadata
version = '0.1'
group = 'org.imesense.dynamicspawncontrol'
archivesBaseName = 'dynamicspawncontrol'

// Java version
sourceCompatibility =
targetCompatibility =
compileJava.sourceCompatibility =
compileJava.targetCompatibility =
    '1.8'

minecraft
{
    // Mappings settings of Minecraft
    mappings channel: 'snapshot', version: '20171003-1.12'

    // Default run configurations
    runs
    {
        client
        {
            // Name player
            args "--username=AmTx"

            // JvmArgs
            jvmArg "-Dfml.coreMods.load=org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            // WorkingDir
            workingDirectory project.file('run')

            // Other properties
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }

        server
        {
            // JvmArgs
            jvmArg "-Dfml.coreMods.load=org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore"
            jvmArg "-Dmixin.hotSwap=true"
            jvmArg "-Dmixin.checks.interfaces=true"

            // WorkingDir
            workingDirectory project.file('run')

            // Other properties
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

mixin
{
    add sourceSets.main, 'mixins.dynamicspawncontrol.refmap.json'
}

dependencies
{
    // Specify the version of Minecraft to use
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    // Use lombok lib
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    implementation 'org.slf4j:slf4j-simple:1.7.36'

    // Use SpongePowered mixins
    implementation 'org.spongepowered:mixin:0.8.5'
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // Use llamalad7 mixinextras
    implementation "io.github.llamalad7:mixinextras-common:0.3.6"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.3.6"

    implementation fg.deobf("curse.maven:fermiumbooter-968474:6386622")

    // Use core mod #1 DivineRPG
    implementation fg.deobf("curse.maven:official-divinerpg-363543:3081433")

    // Use core mod #2 SRParasites
    implementation fg.deobf("curse.maven:scape-and-run-parasites-348025:5370258")

    // Use Byte buddy lib
    implementation 'net.bytebuddy:byte-buddy:1.12.9'

    // Use core mod #3 Special-Mobs
    implementation fg.deobf("curse.maven:special-mobs-59968:3320102")
}

// Get properties into the manifest for reading by the runtime
jar
{
    manifest
    {
        attributes([
            "Specification-Title": "dynamicspawncontrol",
            "Specification-Vendor": "imesense",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"imesense",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "TweakClass": "org.spongepowered.asm.launch.MixinTweaker",
            "FMLCorePlugin": "org.imesense.dynamicspawncontrol.core.plugin.LoadingPluginCore",
            "FMLCorePluginContainsFMLMod": "true",
            "ForceLoadAsMod": "true"
        ])
    }

    exclude 'net/**'
}

// Preferred method to reobfuscate JAR file
jar.finalizedBy('reobfJar')

// Build sources task
tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    from sourceSets.main.resources
    classifier = 'sources'
}

// Build documentation task
tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    from "$buildDir/docs/javadoc"
    classifier = 'javadoc'
}

// Build additional artifacts
artifacts {
    archives sourcesJar
    archives javadocJar
}

publishing
{
    publications
    {
        mavenJava(MavenPublication)
        {
            artifact jar
            artifact sourcesJar
            artifact javadocJar
        }
    }

    repositories
    {
        maven
        {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// Enable packaging of metadata and resources
sourceSets
{
    main
    {
        output.resourcesDir = output.classesDir
    }
}

// Mixins
compileJava
{
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs +=
    [
        "-AdefaultObfuscationEnv=searge",
        "-AoutRefMap=mixins.dynamicspawncontrol.refmap.json"
    ]
}

//tasks.register('copyDependencies', Copy) {
//    from configurations.runtimeClasspath.filter { file ->
//        file.name.contains('mixin-0-7-0-8-compatibility') ||
//                file.name.contains('mixin-booter-419286')
//    }
//
//    into 'build/libs'
//}
//
//build.dependsOn copyDependencies