name: 'Build DynamicSpawnControl (1.12.2)'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/build-dynamicspawncontrol-1.12.2.yml'
      - 'dynamicspawncontrol-1.12.2/**'
      - '!**/*.md'
      - '!**/LICENSE*'

  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/build-dynamicspawncontrol-1.12.2.yml'
      - 'dynamicspawncontrol-1.12.2/**'
      - '!**/*.md'
      - '!**/LICENSE*'

defaults:
  run:
    shell: bash
    working-directory: 'dynamicspawncontrol-1.12.2/'

jobs:
  build-modification:
    name: 'Build modification'

    strategy:
      matrix:
        system:
          - ubuntu-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build modification
        run: ./gradlew build

      - name: Upload modification
        uses: actions/upload-artifact@v4
        with:
          name: dynamicspawncontrol-${{ github.sha }}
          path: forge-1.12.2/build/libs/
